import { prisma } from "@/lib/prisma";
import type { DeadlineType } from "@prisma/client";

/**
 * Recurrence rules for each deadline type (in months).
 * REVISIONE is special: 4 years for the first, 2 years after.
 */
const RECURRENCE_MONTHS: Partial<Record<DeadlineType, number>> = {
  ASSICURAZIONE: 12,
  BOLLO: 12,
  REVISIONE_TACHIGRAFO: 24,
};

const REVISIONE_FIRST_MONTHS = 48; // 4 years
const REVISIONE_SUBSEQUENT_MONTHS = 24; // 2 years

function addMonths(date: Date, months: number): Date {
  const d = new Date(date);
  d.setMonth(d.getMonth() + months);
  return d;
}

/**
 * Get the latest mileage reading for a vehicle, or 0 if none.
 */
async function getLatestKm(vehicleId: string): Promise<number> {
  const reading = await prisma.mileageReading.findFirst({
    where: { vehicleId },
    orderBy: { km: "desc" },
    select: { km: true },
  });
  return reading?.km ?? 0;
}

/**
 * Calculate the next REVISIONE due date based on registrationDate.
 * First revision: 4 years after registration.
 * Subsequent: every 2 years.
 */
function nextRevisionDate(registrationDate: Date, now: Date): Date {
  const firstRevision = addMonths(registrationDate, REVISIONE_FIRST_MONTHS);
  if (firstRevision > now) return firstRevision;

  // Past first revision — calculate next 2-year cycle
  let next = firstRevision;
  while (next <= now) {
    next = addMonths(next, REVISIONE_SUBSEQUENT_MONTHS);
  }
  return next;
}

/**
 * Generate automatic deadlines for a vehicle.
 * Only creates deadlines that don't already have an active (non-completed) entry.
 */
export async function generateAutoDeadlines(vehicleId: string) {
  const vehicle = await prisma.vehicle.findUnique({
    where: { id: vehicleId },
    include: {
      deadlines: { where: { completed: false } },
    },
  });
  if (!vehicle) return;

  const now = new Date();
  const activeTypes = new Set(vehicle.deadlines.map((d) => d.type));
  const toCreate: Array<{
    vehicleId: string;
    type: DeadlineType;
    dueDate: Date;
    dueKm?: number | null;
    reminderDays: number;
    description: string;
    autoGenerated: boolean;
  }> = [];

  // REVISIONE — based on registrationDate
  if (vehicle.registrationDate && !activeTypes.has("REVISIONE")) {
    const dueDate = nextRevisionDate(vehicle.registrationDate, now);
    const isFirst =
      dueDate.getTime() ===
      addMonths(vehicle.registrationDate, REVISIONE_FIRST_MONTHS).getTime();
    toCreate.push({
      vehicleId,
      type: "REVISIONE",
      dueDate,
      reminderDays: 60,
      description: isFirst
        ? "Prima revisione (4 anni da immatricolazione)"
        : "Revisione periodica (ogni 2 anni)",
      autoGenerated: true,
    });
  }

  // ASSICURAZIONE — yearly, generate 1 year from now if none active
  if (!activeTypes.has("ASSICURAZIONE")) {
    toCreate.push({
      vehicleId,
      type: "ASSICURAZIONE",
      dueDate: addMonths(now, 12),
      reminderDays: 30,
      description: "Rinnovo assicurazione (annuale)",
      autoGenerated: true,
    });
  }

  // BOLLO — yearly
  if (!activeTypes.has("BOLLO")) {
    toCreate.push({
      vehicleId,
      type: "BOLLO",
      dueDate: addMonths(now, 12),
      reminderDays: 30,
      description: "Rinnovo bollo (annuale)",
      autoGenerated: true,
    });
  }

  // TAGLIANDO — always 12 months, plus km limit if configured (whichever comes first)
  if (!activeTypes.has("TAGLIANDO")) {
    const dueDate = addMonths(now, 12);
    const dueKm = vehicle.maintenanceIntervalKm
      ? await getLatestKm(vehicleId) + vehicle.maintenanceIntervalKm
      : null;
    const desc = vehicle.maintenanceIntervalKm
      ? `Tagliando programmato (12 mesi o ${vehicle.maintenanceIntervalKm.toLocaleString("it-IT")} km)`
      : "Tagliando programmato (ogni 12 mesi)";
    toCreate.push({
      vehicleId,
      type: "TAGLIANDO",
      dueDate,
      dueKm,
      reminderDays: 30,
      description: desc,
      autoGenerated: true,
    });
  }

  // REVISIONE_TACHIGRAFO — every 2 years (only if vehicle has tachigrafo, i.e. trucks)
  // Not auto-generated by default; user adds first one, then it auto-renews

  if (toCreate.length > 0) {
    await prisma.deadline.createMany({ data: toCreate });
  }
}

/**
 * When a deadline is completed, generate the next one automatically.
 * Uses the dueDate of the completed deadline as the base for recurrence.
 */
export async function generateNextDeadline(deadlineId: string) {
  const deadline = await prisma.deadline.findUnique({
    where: { id: deadlineId },
    include: { vehicle: true },
  });
  if (!deadline || !deadline.completed) return;

  const type = deadline.type;
  let nextDueDate: Date | null = null;
  let nextDueKm: number | null = null;
  let description = "";

  if (type === "REVISIONE") {
    nextDueDate = addMonths(deadline.dueDate, REVISIONE_SUBSEQUENT_MONTHS);
    description = "Revisione periodica (ogni 2 anni)";
  } else if (type === "ASSICURAZIONE") {
    nextDueDate = addMonths(deadline.dueDate, 12);
    description = "Rinnovo assicurazione (annuale)";
  } else if (type === "BOLLO") {
    nextDueDate = addMonths(deadline.dueDate, 12);
    description = "Rinnovo bollo (annuale)";
  } else if (type === "TAGLIANDO") {
    nextDueDate = addMonths(deadline.dueDate, 12);
    if (deadline.vehicle.maintenanceIntervalKm) {
      const currentKm = await getLatestKm(deadline.vehicleId);
      nextDueKm = currentKm + deadline.vehicle.maintenanceIntervalKm;
      description = `Tagliando programmato (12 mesi o ${deadline.vehicle.maintenanceIntervalKm.toLocaleString("it-IT")} km)`;
    } else {
      description = "Tagliando programmato (ogni 12 mesi)";
    }
  } else if (type === "REVISIONE_TACHIGRAFO") {
    nextDueDate = addMonths(deadline.dueDate, RECURRENCE_MONTHS.REVISIONE_TACHIGRAFO!);
    description = "Revisione tachigrafo (ogni 2 anni)";
  }

  if (!nextDueDate) return;

  // Check there isn't already an active deadline of the same type
  const existing = await prisma.deadline.findFirst({
    where: {
      vehicleId: deadline.vehicleId,
      type,
      completed: false,
    },
  });
  if (existing) return;

  await prisma.deadline.create({
    data: {
      vehicleId: deadline.vehicleId,
      type,
      dueDate: nextDueDate,
      dueKm: nextDueKm,
      reminderDays: deadline.reminderDays,
      description,
      autoGenerated: true,
    },
  });
}
