import { prisma } from "@/lib/prisma";
import type { DeadlineType, DocumentType } from "@prisma/client";

/**
 * Recurrence rules for each deadline type (in months).
 * REVISIONE is special: 4 years for the first, 2 years after.
 */
const RECURRENCE_MONTHS: Partial<Record<DeadlineType, number>> = {
  ASSICURAZIONE: 12,
  BOLLO: 12,
  REVISIONE_TACHIGRAFO: 24,
};

const REVISIONE_FIRST_MONTHS = 48; // 4 years
const REVISIONE_SUBSEQUENT_MONTHS = 24; // 2 years
const TAGLIANDO_DEFAULT_MONTHS = 12;
const DOCUMENT_DEADLINE_REMINDER_DAYS = 30;

function addMonths(date: Date, months: number): Date {
  const d = new Date(date);
  d.setMonth(d.getMonth() + months);
  return d;
}

function getTagliandoIntervalMonths(value: number | null | undefined): number {
  if (!value || value < 1) return TAGLIANDO_DEFAULT_MONTHS;
  return value;
}

function buildTagliandoDescription(intervalMonths: number, intervalKm: number | null | undefined): string {
  const monthsPart = `${intervalMonths} ${intervalMonths === 1 ? "mese" : "mesi"}`;
  if (intervalKm) {
    return `Tagliando programmato (${monthsPart} o ${intervalKm.toLocaleString("it-IT")} km)`;
  }
  return `Tagliando programmato (ogni ${monthsPart})`;
}

function buildRevisioneDescription(isFirst: boolean): string {
  return isFirst
    ? "Prima revisione (4 anni da immatricolazione)"
    : "Revisione periodica (ogni 2 anni)";
}

function getReferenceAutoDueDate(
  deadlines: Array<{ type: DeadlineType; autoGenerated: boolean; dueDate: Date }>,
  type: DeadlineType
): Date | null {
  return (
    deadlines
      .filter((d) => d.type === type && d.autoGenerated)
      .slice()
      .sort((a, b) => a.dueDate.getTime() - b.dueDate.getTime())[0]?.dueDate ?? null
  );
}

async function upsertAutoDeadline({
  vehicleId,
  type,
  dueDate,
  dueKm,
  reminderDays,
  description,
  sourceDocumentId,
  skipCreateIfManual = true,
}: {
  vehicleId: string;
  type: DeadlineType;
  dueDate: Date;
  dueKm: number | null;
  reminderDays: number;
  description: string;
  sourceDocumentId?: string | null;
  skipCreateIfManual?: boolean;
}) {
  const active = await prisma.deadline.findMany({
    where: {
      vehicleId,
      type,
      completed: false,
    },
  });

  const activeAuto = active.filter((d) => d.autoGenerated);
  const activeManual = active.filter((d) => !d.autoGenerated);

  if (activeAuto.length > 0) {
    const updateData: {
      dueDate: Date;
      dueKm: number | null;
      reminderDays: number;
      description: string;
      sourceDocumentId?: string | null;
    } = {
      dueDate,
      dueKm,
      reminderDays,
      description,
    };

    if (sourceDocumentId !== undefined) {
      updateData.sourceDocumentId = sourceDocumentId;
    }

    await prisma.deadline.updateMany({
      where: {
        id: { in: activeAuto.map((d) => d.id) },
      },
      data: updateData,
    });
    return;
  }

  if (skipCreateIfManual && activeManual.length > 0) {
    return;
  }

  const createData: {
    vehicleId: string;
    type: DeadlineType;
    dueDate: Date;
    dueKm: number | null;
    reminderDays: number;
    description: string;
    autoGenerated: true;
    sourceDocumentId?: string | null;
  } = {
    vehicleId,
    type,
    dueDate,
    dueKm,
    reminderDays,
    description,
    autoGenerated: true,
  };

  if (sourceDocumentId !== undefined) {
    createData.sourceDocumentId = sourceDocumentId;
  }

  await prisma.deadline.create({
    data: createData,
  });
}

function mapDocumentTypeToDeadlineType(documentType: DocumentType): DeadlineType {
  if (documentType === "ASSICURAZIONE") {
    return "ASSICURAZIONE";
  }
  return "ALTRO";
}

function buildDocumentDeadlineDescription(documentType: DocumentType, documentName: string): string {
  const name = documentName.trim() || "Documento";
  if (documentType === "ASSICURAZIONE") {
    return `Scadenza assicurazione (${name})`;
  }
  if (documentType === "CONTRATTO_NOLEGGIO") {
    return `Scadenza contratto noleggio/leasing (${name})`;
  }
  if (documentType === "CARTA_CIRCOLAZIONE") {
    return `Verifica carta di circolazione (${name})`;
  }
  if (documentType === "LIBRETTO") {
    return `Verifica libretto (${name})`;
  }
  return `Scadenza documento (${name})`;
}

/**
 * Keep automatic REVISIONE deadline aligned with registration date and
 * revision maintenance history.
 */
export async function syncRevisioneDeadline(
  vehicleId: string,
  options?: {
    performedAt?: Date;
    completeExistingAuto?: boolean;
  }
) {
  const vehicle = await prisma.vehicle.findUnique({
    where: { id: vehicleId },
    include: {
      deadlines: {
        where: {
          completed: false,
          type: "REVISIONE",
        },
      },
      maintenanceInterventions: {
        where: { type: "REVISIONE" },
        orderBy: [{ date: "desc" }, { createdAt: "desc" }],
        take: 1,
      },
    },
  });

  if (!vehicle) return;

  const now = options?.performedAt ?? new Date();
  const latestRevision = vehicle.maintenanceInterventions[0] ?? null;
  const activeAuto = vehicle.deadlines.filter((d) => d.autoGenerated);
  const activeManual = vehicle.deadlines.filter((d) => !d.autoGenerated);
  const referenceAuto = activeAuto
    .slice()
    .sort((a, b) => a.dueDate.getTime() - b.dueDate.getTime())[0] ?? null;

  let dueDate: Date | null = null;
  let description = "Revisione periodica (ogni 2 anni)";

  if (options?.performedAt) {
    dueDate = addMonths(options.performedAt, REVISIONE_SUBSEQUENT_MONTHS);
  } else if (latestRevision) {
    dueDate = addMonths(latestRevision.date, REVISIONE_SUBSEQUENT_MONTHS);
  } else if (vehicle.registrationDate) {
    dueDate = nextRevisionDate(vehicle.registrationDate, now);
    const isFirst =
      dueDate.getTime() === addMonths(vehicle.registrationDate, REVISIONE_FIRST_MONTHS).getTime();
    description = buildRevisioneDescription(isFirst);
  } else if (referenceAuto) {
    // Keep existing date stable when no registration date exists.
    dueDate = referenceAuto.dueDate;
  }

  if (!dueDate) {
    return;
  }

  if (options?.completeExistingAuto && activeAuto.length > 0) {
    await prisma.deadline.updateMany({
      where: {
        id: { in: activeAuto.map((d) => d.id) },
      },
      data: {
        completed: true,
        completedDate: now,
      },
    });
  }

  if (!options?.completeExistingAuto && activeAuto.length > 0) {
    await prisma.deadline.updateMany({
      where: {
        id: { in: activeAuto.map((d) => d.id) },
      },
      data: {
        dueDate,
        dueKm: null,
        reminderDays: 60,
        description,
        sourceDocumentId: null,
      },
    });
    return;
  }

  if (activeManual.length > 0) {
    return;
  }

  await prisma.deadline.create({
    data: {
      vehicleId,
      type: "REVISIONE",
      dueDate,
      dueKm: null,
      reminderDays: 60,
      description,
      autoGenerated: true,
      sourceDocumentId: null,
    },
  });
}

/**
 * Create or update automatic deadlines linked to uploaded documents validity.
 */
export async function syncDocumentValidityDeadline(options: {
  vehicleId: string;
  documentId: string;
  documentType: DocumentType;
  documentName: string;
  validTo: Date;
}) {
  const type = mapDocumentTypeToDeadlineType(options.documentType);
  const description = buildDocumentDeadlineDescription(
    options.documentType,
    options.documentName
  );

  if (type === "ASSICURAZIONE") {
    await upsertAutoDeadline({
      vehicleId: options.vehicleId,
      type,
      dueDate: options.validTo,
      dueKm: null,
      reminderDays: DOCUMENT_DEADLINE_REMINDER_DAYS,
      description,
      sourceDocumentId: options.documentId,
      skipCreateIfManual: true,
    });
    return;
  }

  const activeLinked = await prisma.deadline.findFirst({
    where: {
      sourceDocumentId: options.documentId,
      completed: false,
      autoGenerated: true,
    },
  });

  if (activeLinked) {
    await prisma.deadline.update({
      where: { id: activeLinked.id },
      data: {
        dueDate: options.validTo,
        dueKm: null,
        reminderDays: DOCUMENT_DEADLINE_REMINDER_DAYS,
        description,
        type,
      },
    });
    return;
  }

  await prisma.deadline.create({
    data: {
      vehicleId: options.vehicleId,
      type,
      dueDate: options.validTo,
      dueKm: null,
      reminderDays: DOCUMENT_DEADLINE_REMINDER_DAYS,
      description,
      autoGenerated: true,
      sourceDocumentId: options.documentId,
    },
  });
}

/**
 * Keep automatic TAGLIANDO deadline aligned with vehicle configuration and
 * maintenance history. If a tagliando is performed, closes current automatic
 * deadline and creates a new one from the performed date/km.
 */
export async function syncTagliandoDeadline(
  vehicleId: string,
  options?: {
    performedAt?: Date;
    performedKm?: number;
    completeExistingAuto?: boolean;
  }
) {
  const vehicle = await prisma.vehicle.findUnique({
    where: { id: vehicleId },
    include: {
      deadlines: {
        where: {
          completed: false,
          type: "TAGLIANDO",
        },
      },
      maintenanceInterventions: {
        where: { type: "TAGLIANDO" },
        orderBy: [{ date: "desc" }, { createdAt: "desc" }],
        take: 1,
      },
    },
  });

  if (!vehicle) return;

  const now = options?.performedAt ?? new Date();
  const intervalMonths = getTagliandoIntervalMonths(vehicle.maintenanceIntervalMonths);
  const intervalKm = vehicle.maintenanceIntervalKm ?? null;

  const latestTagliando = vehicle.maintenanceInterventions[0] ?? null;
  const activeAuto = vehicle.deadlines.filter((d) => d.autoGenerated);
  const activeManual = vehicle.deadlines.filter((d) => !d.autoGenerated);
  const referenceAuto = activeAuto
    .slice()
    .sort((a, b) => a.dueDate.getTime() - b.dueDate.getTime())[0] ?? null;

  const latestKm = await getLatestKm(vehicleId);

  let dueDate: Date;
  if (options?.performedAt) {
    dueDate = addMonths(options.performedAt, intervalMonths);
  } else if (latestTagliando) {
    dueDate = addMonths(latestTagliando.date, intervalMonths);
  } else if (referenceAuto) {
    // Keep existing date stable when no maintenance anchor exists.
    dueDate = referenceAuto.dueDate;
  } else {
    dueDate = addMonths(now, intervalMonths);
  }

  const dueKm = intervalKm
    ? (options?.performedKm ?? latestTagliando?.km ?? latestKm) + intervalKm
    : null;
  const description = buildTagliandoDescription(intervalMonths, intervalKm);

  if (options?.completeExistingAuto && activeAuto.length > 0) {
    await prisma.deadline.updateMany({
      where: {
        id: { in: activeAuto.map((d) => d.id) },
      },
      data: {
        completed: true,
        completedDate: now,
      },
    });
  }

  if (!options?.completeExistingAuto && activeAuto.length > 0) {
    await prisma.deadline.updateMany({
      where: {
        id: { in: activeAuto.map((d) => d.id) },
      },
      data: {
        dueDate,
        dueKm,
        reminderDays: 30,
        description,
      },
    });
    return;
  }

  if (activeManual.length > 0) {
    return;
  }

  await prisma.deadline.create({
    data: {
      vehicleId,
      type: "TAGLIANDO",
      dueDate,
      dueKm,
      reminderDays: 30,
      description,
      autoGenerated: true,
    },
  });
}

/**
 * Get the latest mileage reading for a vehicle, or 0 if none.
 */
async function getLatestKm(vehicleId: string): Promise<number> {
  const reading = await prisma.mileageReading.findFirst({
    where: { vehicleId },
    orderBy: { km: "desc" },
    select: { km: true },
  });
  return reading?.km ?? 0;
}

/**
 * Calculate the next REVISIONE due date based on registrationDate.
 * First revision: 4 years after registration.
 * Subsequent: every 2 years.
 */
function nextRevisionDate(registrationDate: Date, now: Date): Date {
  const firstRevision = addMonths(registrationDate, REVISIONE_FIRST_MONTHS);
  if (firstRevision > now) return firstRevision;

  // Past first revision — calculate next 2-year cycle
  let next = firstRevision;
  while (next <= now) {
    next = addMonths(next, REVISIONE_SUBSEQUENT_MONTHS);
  }
  return next;
}

/**
 * Generate automatic deadlines for a vehicle.
 * Only creates deadlines that don't already have an active (non-completed) entry.
 */
export async function generateAutoDeadlines(vehicleId: string) {
  const vehicle = await prisma.vehicle.findUnique({
    where: { id: vehicleId },
    include: {
      deadlines: {
        where: {
          completed: false,
          type: {
            in: ["REVISIONE", "ASSICURAZIONE", "BOLLO"],
          },
        },
      },
    },
  });
  if (!vehicle) return;

  const now = new Date();

  await syncRevisioneDeadline(vehicleId, { completeExistingAuto: false });

  const insuranceDueDate =
    getReferenceAutoDueDate(vehicle.deadlines, "ASSICURAZIONE") ??
    addMonths(now, RECURRENCE_MONTHS.ASSICURAZIONE!);
  await upsertAutoDeadline({
    vehicleId,
    type: "ASSICURAZIONE",
    dueDate: insuranceDueDate,
    dueKm: null,
    reminderDays: 30,
    description: "Rinnovo assicurazione (annuale)",
    skipCreateIfManual: true,
  });

  const bolloDueDate =
    getReferenceAutoDueDate(vehicle.deadlines, "BOLLO") ??
    addMonths(now, RECURRENCE_MONTHS.BOLLO!);
  await upsertAutoDeadline({
    vehicleId,
    type: "BOLLO",
    dueDate: bolloDueDate,
    dueKm: null,
    reminderDays: 30,
    description: "Rinnovo bollo (annuale)",
    skipCreateIfManual: true,
  });

  await syncTagliandoDeadline(vehicleId);
}

export type AutoDeadlineReconcileResult = {
  vehiclesProcessed: number;
  documentsProcessed: number;
  staleDocumentDeadlinesDeleted: number;
};

/**
 * Periodic autonomous reconciliation for automatic deadlines.
 *
 * This is intentionally idempotent: running it repeatedly should converge
 * to the same state and acts as a safety net if an event trigger is missed.
 */
export async function reconcileAutoDeadlines(options?: {
  vehicleIds?: string[];
}): Promise<AutoDeadlineReconcileResult> {
  const vehicles = options?.vehicleIds?.length
    ? await prisma.vehicle.findMany({
        where: { id: { in: options.vehicleIds } },
        select: { id: true },
      })
    : await prisma.vehicle.findMany({
        select: { id: true },
      });

  let documentsProcessed = 0;
  let staleDocumentDeadlinesDeleted = 0;

  for (const vehicle of vehicles) {
    await generateAutoDeadlines(vehicle.id);

    const validDocuments = await prisma.document.findMany({
      where: {
        vehicleId: vehicle.id,
        tripAnomalyId: null,
        validTo: { not: null },
      },
      select: {
        id: true,
        type: true,
        name: true,
        validTo: true,
      },
    });

    for (const document of validDocuments) {
      await syncDocumentValidityDeadline({
        vehicleId: vehicle.id,
        documentId: document.id,
        documentType: document.type,
        documentName: document.name,
        validTo: document.validTo as Date,
      });
      documentsProcessed += 1;
    }

    const validDocumentIds = validDocuments.map((document) => document.id);
    const staleDelete = await prisma.deadline.deleteMany({
      where: {
        vehicleId: vehicle.id,
        autoGenerated: true,
        completed: false,
        NOT: { sourceDocumentId: null },
        ...(validDocumentIds.length > 0
          ? { sourceDocumentId: { notIn: validDocumentIds } }
          : {}),
      },
    });

    staleDocumentDeadlinesDeleted += staleDelete.count;
  }

  return {
    vehiclesProcessed: vehicles.length,
    documentsProcessed,
    staleDocumentDeadlinesDeleted,
  };
}

/**
 * When a deadline is completed, generate the next one automatically.
 * Uses the dueDate of the completed deadline as the base for recurrence.
 */
export async function generateNextDeadline(deadlineId: string) {
  const deadline = await prisma.deadline.findUnique({
    where: { id: deadlineId },
    include: { vehicle: true },
  });
  if (!deadline || !deadline.completed) return;

  const type = deadline.type;
  let nextDueDate: Date | null = null;
  let nextDueKm: number | null = null;
  let description = "";

  if (type === "REVISIONE") {
    const baseDate = deadline.completedDate ?? deadline.dueDate;
    nextDueDate = addMonths(baseDate, REVISIONE_SUBSEQUENT_MONTHS);
    description = "Revisione periodica (ogni 2 anni)";
  } else if (type === "ASSICURAZIONE") {
    const baseDate = deadline.completedDate ?? deadline.dueDate;
    nextDueDate = addMonths(baseDate, 12);
    description = "Rinnovo assicurazione (annuale)";
  } else if (type === "BOLLO") {
    const baseDate = deadline.completedDate ?? deadline.dueDate;
    nextDueDate = addMonths(baseDate, 12);
    description = "Rinnovo bollo (annuale)";
  } else if (type === "TAGLIANDO") {
    const intervalMonths = getTagliandoIntervalMonths(deadline.vehicle.maintenanceIntervalMonths);
    const baseDate = deadline.completedDate ?? deadline.dueDate;
    nextDueDate = addMonths(baseDate, intervalMonths);
    if (deadline.vehicle.maintenanceIntervalKm) {
      const currentKm = await getLatestKm(deadline.vehicleId);
      nextDueKm = currentKm + deadline.vehicle.maintenanceIntervalKm;
    }
    description = buildTagliandoDescription(intervalMonths, deadline.vehicle.maintenanceIntervalKm);
  } else if (type === "REVISIONE_TACHIGRAFO") {
    const baseDate = deadline.completedDate ?? deadline.dueDate;
    nextDueDate = addMonths(baseDate, RECURRENCE_MONTHS.REVISIONE_TACHIGRAFO!);
    description = "Revisione tachigrafo (ogni 2 anni)";
  }

  if (!nextDueDate) return;

  // Check there isn't already an active deadline of the same type
  const existing = await prisma.deadline.findFirst({
    where: {
      vehicleId: deadline.vehicleId,
      type,
      completed: false,
    },
  });
  if (existing) return;

  await prisma.deadline.create({
    data: {
      vehicleId: deadline.vehicleId,
      type,
      dueDate: nextDueDate,
      dueKm: nextDueKm,
      reminderDays: deadline.reminderDays,
      description,
      autoGenerated: true,
    },
  });
}
