import { prisma } from "@/lib/prisma";
import { getSessionUser, canManageDeadlines, isAdmin } from "@/lib/auth-utils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { deadlineTypeLabels } from "@/lib/labels";
import { differenceInDays } from "date-fns";
import { Zap, PenLine, Search } from "lucide-react";
import { DeadlineForm } from "@/components/deadline-form";
import { DeadlineTableClient, type DeadlineItem } from "@/components/deadline-table";

export default async function ScadenzePage({
  searchParams,
}: {
  searchParams: Promise<{ status?: string; type?: string; q?: string }>;
}) {
  const user = await getSessionUser();
  const params = await searchParams;
  const canCreate = canManageDeadlines(user.role);
  const canEditDelete = isAdmin(user.role);
  const now = new Date();

  const whereVehicle =
    user.role === "DRIVER" ? { assignedDriverId: user.id } : {};

  const where: Record<string, unknown> = { vehicle: whereVehicle };

  if (params.status === "overdue") {
    where.completed = false;
    where.dueDate = { lt: now };
  } else if (params.status === "upcoming") {
    where.completed = false;
    where.dueDate = {
      gte: now,
      lte: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000),
    };
  } else if (params.status === "completed") {
    where.completed = true;
  } else if (params.status === "active") {
    where.completed = false;
  }

  if (params.type) {
    where.type = params.type;
  }

  const deadlines = await prisma.deadline.findMany({
    where,
    include: { vehicle: true },
    orderBy: { dueDate: "asc" },
  });

  const deadlineIds = deadlines.map((d) => d.id);
  const plannedByDeadline = deadlineIds.length
    ? await prisma.plannedMaintenance.findMany({
        where: {
          sourceDeadlineId: { in: deadlineIds },
          status: "PLANNED",
        },
        select: { sourceDeadlineId: true },
      })
    : [];
  const deadlineWithPlanned = new Set(
    plannedByDeadline
      .map((item) => item.sourceDeadlineId)
      .filter((value): value is string => Boolean(value))
  );

  const vehicles = canCreate
    ? await prisma.vehicle.findMany({
        where: { ...whereVehicle, status: "ACTIVE" },
        select: { id: true, plate: true },
        orderBy: { plate: "asc" },
      })
    : [];

  // Fetch latest km for vehicles that have km-based deadlines
  const vehicleIdsWithKm = [...new Set(
    deadlines.filter((d) => d.dueKm).map((d) => d.vehicleId)
  )];
  const latestKmMap = new Map<string, number>();
  for (const vid of vehicleIdsWithKm) {
    const reading = await prisma.mileageReading.findFirst({
      where: { vehicleId: vid },
      orderBy: { km: "desc" },
      select: { km: true },
    });
    latestKmMap.set(vid, reading?.km ?? 0);
  }

  const autoDeadlines = deadlines.filter((d) => d.autoGenerated);
  const manualDeadlines = deadlines.filter((d) => !d.autoGenerated);

  // Client-side text search
  const searchQuery = (params.q || "").toLowerCase().trim();
  const searchFilter = (items: typeof deadlines) => {
    if (!searchQuery) return items;
    return items.filter((d) => {
      const haystack = [
        d.vehicle.plate,
        deadlineTypeLabels[d.type],
        d.description || "",
      ].join(" ").toLowerCase();
      return searchQuery.split(/\s+/).every((w) => haystack.includes(w));
    });
  };
  const filteredAuto = searchFilter(autoDeadlines);
  const filteredManual = searchFilter(manualDeadlines);

  function getStatus(d: { completed: boolean; dueDate: Date; dueKm: number | null; vehicleId: string }) {
    if (d.completed) return "completed";
    if (d.dueKm) {
      const currentKm = latestKmMap.get(d.vehicleId) ?? 0;
      if (currentKm >= d.dueKm) return "overdue";
      if (currentKm >= d.dueKm - 1000) return "upcoming";
    }
    if (d.dueDate < now) return "overdue";
    const diff = differenceInDays(d.dueDate, now);
    if (diff <= 30) return "upcoming";
    return "ok";
  }

  function toItems(list: typeof deadlines): DeadlineItem[] {
    return list.map((d) => ({
      id: d.id,
      vehicleId: d.vehicleId,
      vehiclePlate: d.vehicle.plate,
      type: d.type,
      dueDate: d.dueDate.toISOString(),
      dueKm: d.dueKm,
      reminderDays: d.reminderDays,
      description: d.description,
      completed: d.completed,
      status: getStatus(d),
      hasPlannedMaintenance: deadlineWithPlanned.has(d.id),
    }));
  }

  return (
    <div className="space-y-6">
        <DeadlineForm vehicles={vehicles} canCreate={canCreate} />

      {/* Filters */}
      <form className="flex flex-wrap gap-3 items-center">
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <input
            name="q"
            defaultValue={params.q || ""}
            placeholder="Cerca per targa, tipo, descrizione..."
            className="w-full rounded-lg border bg-background pl-10 pr-3 py-2 text-sm"
          />
        </div>
        <select
          name="status"
          defaultValue={params.status || ""}
          className="rounded-md border bg-background px-3 py-2 text-sm"
        >
          <option value="">Tutte</option>
          <option value="overdue">Scadute</option>
          <option value="upcoming">In scadenza (30gg)</option>
          <option value="active">Attive</option>
          <option value="completed">Completate</option>
        </select>
        <select
          name="type"
          defaultValue={params.type || ""}
          className="rounded-md border bg-background px-3 py-2 text-sm"
        >
          <option value="">Tutti i tipi</option>
          <option value="TAGLIANDO">Tagliando</option>
          <option value="REVISIONE">Revisione</option>
          <option value="ASSICURAZIONE">Assicurazione</option>
          <option value="BOLLO">Bollo</option>
          <option value="REVISIONE_TACHIGRAFO">Rev. Tachigrafo</option>
          <option value="ALTRO">Altro</option>
        </select>
        <Button type="submit" variant="secondary" size="sm">
          Filtra
        </Button>
      </form>

      {/* Automatic deadlines - primary */}
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <Zap className="h-5 w-5 text-purple-600" />
          <h2 className="text-lg font-semibold">Scadenze Automatiche</h2>
          <Badge variant="outline" className="bg-purple-50 text-purple-700">
            {filteredAuto.length}
          </Badge>
        </div>
        <div className="rounded-lg border bg-card">
          <DeadlineTableClient items={toItems(filteredAuto)} canPlan={canCreate} canEditDelete={canEditDelete} />
        </div>
      </div>

      {/* Manual deadlines - secondary */}
      {filteredManual.length > 0 && (
        <div className="space-y-2 opacity-75">
          <div className="flex items-center gap-2">
            <PenLine className="h-4 w-4 text-muted-foreground" />
            <h2 className="text-sm font-medium text-muted-foreground">Scadenze Manuali</h2>
            <Badge variant="outline" className="text-xs">
              {filteredManual.length}
            </Badge>
          </div>
          <div className="rounded-lg border bg-card">
            <DeadlineTableClient items={toItems(filteredManual)} canPlan={canCreate} canEditDelete={canEditDelete} showDelete />
          </div>
        </div>
      )}
    </div>
  );
}
