import { prisma } from "@/lib/prisma";
import { getSessionUser, canManageDeadlines } from "@/lib/auth-utils";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { deadlineTypeLabels } from "@/lib/labels";
import { toggleDeadlineComplete, deleteDeadline } from "@/lib/actions/deadline-actions";
import { differenceInDays } from "date-fns";
import { Check, RotateCcw, Zap, PenLine, Trash2 } from "lucide-react";

export default async function ScadenzePage({
  searchParams,
}: {
  searchParams: Promise<{ status?: string; type?: string }>;
}) {
  const user = await getSessionUser();
  const params = await searchParams;
  const canManage = canManageDeadlines(user.role);
  const now = new Date();

  const whereVehicle =
    user.role === "DRIVER" ? { assignedDriverId: user.id } : {};

  const where: Record<string, unknown> = { vehicle: whereVehicle };

  if (params.status === "overdue") {
    where.completed = false;
    where.dueDate = { lt: now };
  } else if (params.status === "upcoming") {
    where.completed = false;
    where.dueDate = {
      gte: now,
      lte: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000),
    };
  } else if (params.status === "completed") {
    where.completed = true;
  } else if (params.status === "active") {
    where.completed = false;
  }

  if (params.type) {
    where.type = params.type;
  }

  const deadlines = await prisma.deadline.findMany({
    where,
    include: { vehicle: true },
    orderBy: { dueDate: "asc" },
  });

  // Fetch latest km for vehicles that have km-based deadlines
  const vehicleIdsWithKm = [...new Set(
    deadlines.filter((d) => d.dueKm).map((d) => d.vehicleId)
  )];
  const latestKmMap = new Map<string, number>();
  for (const vid of vehicleIdsWithKm) {
    const reading = await prisma.mileageReading.findFirst({
      where: { vehicleId: vid },
      orderBy: { km: "desc" },
      select: { km: true },
    });
    latestKmMap.set(vid, reading?.km ?? 0);
  }

  const autoDeadlines = deadlines.filter((d) => d.autoGenerated);
  const manualDeadlines = deadlines.filter((d) => !d.autoGenerated);

  function getStatus(d: { completed: boolean; dueDate: Date; dueKm: number | null; vehicleId: string }) {
    if (d.completed) return "completed";
    if (d.dueKm) {
      const currentKm = latestKmMap.get(d.vehicleId) ?? 0;
      if (currentKm >= d.dueKm) return "overdue";
      if (currentKm >= d.dueKm - 1000) return "upcoming";
    }
    if (d.dueDate < now) return "overdue";
    const diff = differenceInDays(d.dueDate, now);
    if (diff <= 30) return "upcoming";
    return "ok";
  }

  const statusBadge: Record<string, { label: string; className: string }> = {
    completed: { label: "Completata", className: "bg-green-100 text-green-800" },
    overdue: { label: "Scaduta", className: "bg-red-100 text-red-800" },
    upcoming: { label: "In scadenza", className: "bg-orange-100 text-orange-800" },
    ok: { label: "OK", className: "bg-blue-100 text-blue-800" },
  };

  function DeadlineTable({ items, showDelete = false }: { items: typeof deadlines; showDelete?: boolean }) {
    return (
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Targa</TableHead>
            <TableHead>Tipo</TableHead>
            <TableHead>Data Scadenza</TableHead>
            <TableHead>Scadenza Km</TableHead>
            <TableHead>Stato</TableHead>
            <TableHead>Descrizione</TableHead>
            {canManage && <TableHead>Azioni</TableHead>}
          </TableRow>
        </TableHeader>
        <TableBody>
          {items.length === 0 ? (
            <TableRow>
              <TableCell colSpan={canManage ? 7 : 6} className="text-center text-muted-foreground py-8">
                Nessuna scadenza trovata
              </TableCell>
            </TableRow>
          ) : (
            items.map((d) => {
              const status = getStatus(d);
              const badge = statusBadge[status];
              return (
                <TableRow key={d.id}>
                  <TableCell>
                    <Link
                      href={`/mezzi/${d.vehicleId}`}
                      className="font-mono font-semibold hover:underline"
                    >
                      {d.vehicle.plate}
                    </Link>
                  </TableCell>
                  <TableCell>
                    <Badge variant="outline">
                      {deadlineTypeLabels[d.type]}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    {d.dueDate.toLocaleDateString("it-IT")}
                  </TableCell>
                  <TableCell>
                    {d.dueKm ? `${d.dueKm.toLocaleString("it-IT")} km` : "—"}
                  </TableCell>
                  <TableCell>
                    <Badge variant="outline" className={badge.className}>
                      {badge.label}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-muted-foreground max-w-xs truncate">
                    {d.description || "—"}
                  </TableCell>
                  {canManage && (
                    <TableCell>
                      <div className="flex gap-1">
                        <form action={async () => { "use server"; await toggleDeadlineComplete(d.id); }}>
                          <Button
                            type="submit"
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8"
                            title={d.completed ? "Riapri" : "Completa"}
                          >
                            {d.completed ? (
                              <RotateCcw className="h-4 w-4" />
                            ) : (
                              <Check className="h-4 w-4" />
                            )}
                          </Button>
                        </form>
                        {showDelete && (
                          <form action={async () => { "use server"; await deleteDeadline(d.id); }}>
                            <Button
                              type="submit"
                              variant="ghost"
                              size="icon"
                              className="h-8 w-8 text-destructive"
                              title="Elimina"
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </form>
                        )}
                      </div>
                    </TableCell>
                  )}
                </TableRow>
              );
            })
          )}
        </TableBody>
      </Table>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Scadenze</h1>
        <p className="text-muted-foreground">
          Gestione scadenze flotta aziendale
        </p>
      </div>

      {/* Filters */}
      <form className="flex flex-wrap gap-3">
        <select
          name="status"
          defaultValue={params.status || ""}
          className="rounded-md border bg-background px-3 py-2 text-sm"
        >
          <option value="">Tutte</option>
          <option value="overdue">Scadute</option>
          <option value="upcoming">In scadenza (30gg)</option>
          <option value="active">Attive</option>
          <option value="completed">Completate</option>
        </select>
        <select
          name="type"
          defaultValue={params.type || ""}
          className="rounded-md border bg-background px-3 py-2 text-sm"
        >
          <option value="">Tutti i tipi</option>
          <option value="TAGLIANDO">Tagliando</option>
          <option value="REVISIONE">Revisione</option>
          <option value="ASSICURAZIONE">Assicurazione</option>
          <option value="BOLLO">Bollo</option>
          <option value="REVISIONE_TACHIGRAFO">Rev. Tachigrafo</option>
          <option value="ALTRO">Altro</option>
        </select>
        <Button type="submit" variant="secondary" size="sm">
          Filtra
        </Button>
      </form>

      {/* Automatic deadlines - primary */}
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <Zap className="h-5 w-5 text-purple-600" />
          <h2 className="text-lg font-semibold">Scadenze Automatiche</h2>
          <Badge variant="outline" className="bg-purple-50 text-purple-700">
            {autoDeadlines.length}
          </Badge>
        </div>
        <div className="rounded-lg border bg-card">
          <DeadlineTable items={autoDeadlines} />
        </div>
      </div>

      {/* Manual deadlines - secondary */}
      {manualDeadlines.length > 0 && (
        <div className="space-y-2 opacity-75">
          <div className="flex items-center gap-2">
            <PenLine className="h-4 w-4 text-muted-foreground" />
            <h2 className="text-sm font-medium text-muted-foreground">Scadenze Manuali</h2>
            <Badge variant="outline" className="text-xs">
              {manualDeadlines.length}
            </Badge>
          </div>
          <div className="rounded-lg border bg-card">
            <DeadlineTable items={manualDeadlines} showDelete />
          </div>
        </div>
      )}
    </div>
  );
}
