"use server";

import { prisma } from "@/lib/prisma";
import { getSessionUser, canManageDeadlines, canEditDeleteEntries } from "@/lib/auth-utils";
import { deadlineSchema, manualDeadlineUpdateSchema } from "@/lib/validators";
import { revalidatePath } from "next/cache";
import { generateNextDeadline } from "@/lib/auto-deadlines";
import type { DeadlineType } from "@prisma/client";

function addMonths(date: Date, months: number): Date {
  const d = new Date(date);
  d.setMonth(d.getMonth() + months);
  return d;
}

async function removeGeneratedNextOnReopen(deadline: {
  id: string;
  vehicleId: string;
  type: DeadlineType;
  dueDate: Date;
  completedDate: Date | null;
  autoGenerated: boolean;
  sourceDocumentId: string | null;
}) {
  if (!deadline.autoGenerated) return;

  const anchor = deadline.completedDate ?? deadline.dueDate;
  let expectedDueDate: Date | null = null;

  if (deadline.type === "REVISIONE") {
    expectedDueDate = addMonths(anchor, 24);
  } else if (deadline.type === "ASSICURAZIONE") {
    expectedDueDate = addMonths(anchor, 12);
  } else if (deadline.type === "BOLLO") {
    expectedDueDate = addMonths(anchor, 12);
  } else if (deadline.type === "REVISIONE_TACHIGRAFO") {
    expectedDueDate = addMonths(anchor, 24);
  } else if (deadline.type === "TAGLIANDO") {
    const vehicle = await prisma.vehicle.findUnique({
      where: { id: deadline.vehicleId },
      select: { maintenanceIntervalMonths: true },
    });
    const months = vehicle?.maintenanceIntervalMonths && vehicle.maintenanceIntervalMonths > 0
      ? vehicle.maintenanceIntervalMonths
      : 12;
    expectedDueDate = addMonths(anchor, months);
  }

  if (!expectedDueDate) return;

  const exactMatch = await prisma.deadline.findFirst({
    where: {
      vehicleId: deadline.vehicleId,
      type: deadline.type,
      id: { not: deadline.id },
      completed: false,
      autoGenerated: true,
      sourceDocumentId: null,
      dueDate: expectedDueDate,
    },
    orderBy: { createdAt: "desc" },
  });

  if (exactMatch) {
    await prisma.deadline.delete({ where: { id: exactMatch.id } });
    return;
  }

  // Fallback for cases where config changed after completion (e.g. tagliando interval).
  const fallbackMatch = await prisma.deadline.findFirst({
    where: {
      vehicleId: deadline.vehicleId,
      type: deadline.type,
      id: { not: deadline.id },
      completed: false,
      autoGenerated: true,
      sourceDocumentId: null,
      dueDate: { gt: deadline.dueDate },
    },
    orderBy: [{ dueDate: "asc" }, { createdAt: "asc" }],
  });

  if (fallbackMatch) {
    await prisma.deadline.delete({ where: { id: fallbackMatch.id } });
  }
}

export async function createDeadline(
  _prevState: { error?: string; success?: boolean } | undefined,
  formData: FormData
) {
  const user = await getSessionUser();
  if (!canManageDeadlines(user.role)) {
    return { error: "Non autorizzato" };
  }

  const raw = Object.fromEntries(formData.entries());
  const parsed = deadlineSchema.safeParse(raw);
  if (!parsed.success) {
    return { error: parsed.error.issues[0].message };
  }

  await prisma.deadline.create({ data: parsed.data });

  revalidatePath(`/mezzi/${parsed.data.vehicleId}`);
  revalidatePath("/scadenze");
  return { success: true };
}

export async function toggleDeadlineComplete(deadlineId: string) {
  const user = await getSessionUser();
  if (!canEditDeleteEntries(user.role)) {
    return { error: "Non autorizzato" };
  }

  const deadline = await prisma.deadline.findUnique({
    where: { id: deadlineId },
  });
  if (!deadline) return { error: "Scadenza non trovata" };

  await prisma.deadline.update({
    where: { id: deadlineId },
    data: {
      completed: !deadline.completed,
      completedDate: !deadline.completed ? new Date() : null,
    },
  });

  // When completing a deadline, automatically generate the next one
  if (!deadline.completed) {
    await generateNextDeadline(deadlineId);
  } else {
    await removeGeneratedNextOnReopen(deadline);
  }

  revalidatePath(`/mezzi/${deadline.vehicleId}`);
  revalidatePath("/scadenze");
  revalidatePath("/");
}

export async function deleteDeadline(deadlineId: string) {
  const user = await getSessionUser();
  if (!canEditDeleteEntries(user.role)) {
    return { error: "Non autorizzato" };
  }

  const deadline = await prisma.deadline.findUnique({
    where: { id: deadlineId },
  });
  if (!deadline) return { error: "Scadenza non trovata" };

  await prisma.deadline.delete({ where: { id: deadlineId } });

  revalidatePath(`/mezzi/${deadline.vehicleId}`);
  revalidatePath("/scadenze");
  revalidatePath("/");
}

export async function updateManualDeadline(
  _prevState: { error?: string; success?: boolean } | undefined,
  formData: FormData
) {
  const user = await getSessionUser();
  if (!canEditDeleteEntries(user.role)) {
    return { error: "Non autorizzato" };
  }

  const raw = Object.fromEntries(formData.entries());
  const parsed = manualDeadlineUpdateSchema.safeParse(raw);
  if (!parsed.success) {
    return { error: parsed.error.issues[0].message };
  }

  const existing = await prisma.deadline.findUnique({
    where: { id: parsed.data.deadlineId },
    select: { id: true, vehicleId: true, autoGenerated: true },
  });

  if (!existing) {
    return { error: "Scadenza non trovata" };
  }

  if (existing.autoGenerated) {
    return { error: "Le scadenze automatiche non sono modificabili" };
  }

  await prisma.deadline.update({
    where: { id: existing.id },
    data: {
      type: parsed.data.type,
      dueDate: parsed.data.dueDate,
      dueKm: parsed.data.dueKm,
      reminderDays: parsed.data.reminderDays,
      description: parsed.data.description || null,
    },
  });

  revalidatePath(`/mezzi/${existing.vehicleId}`);
  revalidatePath("/scadenze");
  revalidatePath("/");
  return { success: true };
}
