-- AlterTable
ALTER TABLE "Deadline" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "Vehicle" ADD COLUMN     "maintenanceIntervalKm" INTEGER,
ADD COLUMN     "maintenanceIntervalMonths" INTEGER DEFAULT 12,
ADD COLUMN     "registrationDate" TIMESTAMP(3);
