"use client";

import { Fragment, useActionState, useEffect, useState } from "react";
import { createDeadline, toggleDeadlineComplete, deleteDeadline, updateManualDeadline } from "@/lib/actions/deadline-actions";
import { SubmitButton } from "@/components/ui/submit-button";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Plus, Check, Trash2, RotateCcw, Zap, PenLine, Pencil } from "lucide-react";
import { deadlineTypeLabels } from "@/lib/labels";

type DeadlineRecord = {
  id: string;
  type: string;
  dueDate: string;
  dueKm: number | null;
  reminderDays: number;
  description: string | null;
  completed: boolean;
  completedDate: string | null;
  autoGenerated: boolean;
};

export function DeadlineTab({
  vehicleId,
  deadlines,
  currentKm,
  canCreate,
  canEditDelete,
}: {
  vehicleId: string;
  deadlines: DeadlineRecord[];
  currentKm: number;
  canCreate: boolean;
  canEditDelete: boolean;
}) {
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [state, formAction] = useActionState(createDeadline, undefined);

  const now = new Date();

  const autoDeadlines = deadlines.filter((d) => d.autoGenerated);
  const manualDeadlines = deadlines.filter((d) => !d.autoGenerated);
  const colSpan = canEditDelete ? 7 : 6;

  function getDeadlineStatus(d: DeadlineRecord) {
    if (d.completed) return "completed";
    // Check km-based expiry first (for tagliando)
    if (d.dueKm && currentKm >= d.dueKm) return "overdue";
    const due = new Date(d.dueDate);
    if (due < now) return "overdue";
    // Upcoming: within 30 days or within 1000 km of limit
    if (d.dueKm && currentKm >= d.dueKm - 1000) return "upcoming";
    const diff = (due.getTime() - now.getTime()) / (1000 * 60 * 60 * 24);
    if (diff <= 30) return "upcoming";
    return "ok";
  }

  const statusBadge: Record<string, { label: string; className: string }> = {
    completed: { label: "Completata", className: "bg-green-100 text-green-800" },
    overdue: { label: "Scaduta", className: "bg-red-100 text-red-800" },
    upcoming: { label: "In scadenza", className: "bg-orange-100 text-orange-800" },
    ok: { label: "OK", className: "bg-blue-100 text-blue-800" },
  };

  const renderDeadlineTableRows = (items: DeadlineRecord[]) => {
    if (items.length === 0) {
      return (
        <TableRow>
          <TableCell colSpan={colSpan} className="text-center text-muted-foreground py-6">
            Nessuna scadenza
          </TableCell>
        </TableRow>
      );
    }
    return (
      <>
        {items.map((d) => {
          const status = getDeadlineStatus(d);
          const badge = statusBadge[status];
          return (
            <Fragment key={d.id}>
              <TableRow key={d.id}>
                <TableCell>
                  <Badge variant="outline">
                    {deadlineTypeLabels[d.type]}
                  </Badge>
                </TableCell>
                <TableCell>
                  {new Date(d.dueDate).toLocaleDateString("it-IT")}
                </TableCell>
                <TableCell>
                  {d.dueKm ? `${d.dueKm.toLocaleString("it-IT")} km` : "—"}
                </TableCell>
                <TableCell>
                  <Badge variant="outline" className={badge.className}>
                    {badge.label}
                  </Badge>
                </TableCell>
                <TableCell>{d.reminderDays}gg</TableCell>
                <TableCell className="text-muted-foreground max-w-xs truncate">
                  {d.description || "—"}
                </TableCell>
                {canEditDelete && (
                  <TableCell>
                    <div className="flex gap-1">
                      <form action={async () => { await toggleDeadlineComplete(d.id); }}>
                        <Button type="submit" variant="ghost" size="icon" className="h-8 w-8" title={d.completed ? "Riapri" : "Completa"}>
                          {d.completed ? (
                            <RotateCcw className="h-4 w-4" />
                          ) : (
                            <Check className="h-4 w-4" />
                          )}
                        </Button>
                      </form>
                      {!d.autoGenerated && (
                        <Button
                          type="button"
                          variant="ghost"
                          size="icon"
                          className="h-8 w-8"
                          title="Modifica"
                          onClick={() => setEditingId(editingId === d.id ? null : d.id)}
                        >
                          <Pencil className="h-4 w-4" />
                        </Button>
                      )}
                      <form action={async () => { await deleteDeadline(d.id); }}>
                        <Button type="submit" variant="ghost" size="icon" className="h-8 w-8 text-destructive" title="Elimina">
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </form>
                    </div>
                  </TableCell>
                )}
              </TableRow>
              {editingId === d.id && !d.autoGenerated ? (
                <ManualDeadlineEditRow item={d} colSpan={colSpan} onClose={() => setEditingId(null)} />
              ) : null}
            </Fragment>
          );
        })}
      </>
    );
  };

  const tableHeader = (
    <TableHeader>
      <TableRow>
        <TableHead>Tipo</TableHead>
        <TableHead>Data Scadenza</TableHead>
        <TableHead>Scadenza Km</TableHead>
        <TableHead>Stato</TableHead>
        <TableHead>Preavviso</TableHead>
        <TableHead>Descrizione</TableHead>
        {canEditDelete && <TableHead>Azioni</TableHead>}
      </TableRow>
    </TableHeader>
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h3 className="font-semibold">Scadenze</h3>
        {canCreate && (
          <Button
            variant="outline"
            size="sm"
            onClick={() => setShowForm(!showForm)}
          >
            <Plus className="mr-2 h-4 w-4" />
            Nuova Scadenza
          </Button>
        )}
      </div>

      {showForm && canCreate && (
        <form action={formAction} className="rounded-lg border p-4 space-y-4">
          {state?.error && (
            <div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">
              {state.error}
            </div>
          )}
          {state?.success && (
            <div className="rounded-md bg-green-50 p-3 text-sm text-green-700">
              Scadenza salvata
            </div>
          )}
          <input type="hidden" name="vehicleId" value={vehicleId} />
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div className="space-y-2">
              <Label htmlFor="type">Tipo *</Label>
              <select
                id="type"
                name="type"
                className="w-full rounded-md border bg-background px-3 py-2 text-sm"
                required
              >
                <option value="TAGLIANDO">Tagliando</option>
                <option value="REVISIONE">Revisione</option>
                <option value="ASSICURAZIONE">Assicurazione</option>
                <option value="BOLLO">Bollo</option>
                <option value="REVISIONE_TACHIGRAFO">Rev. Tachigrafo</option>
                <option value="ALTRO">Altro</option>
              </select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="dueDate">Data Scadenza *</Label>
              <Input id="dueDate" name="dueDate" type="date" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="reminderDays">Preavviso (giorni)</Label>
              <Input
                id="reminderDays"
                name="reminderDays"
                type="number"
                defaultValue={30}
                min={1}
                max={365}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="description">Descrizione</Label>
              <Input id="description" name="description" />
            </div>
          </div>
          <SubmitButton size="sm" pendingText="Salvataggio...">
            Salva
          </SubmitButton>
        </form>
      )}

      {/* Automatic deadlines - primary */}
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <Zap className="h-4 w-4 text-purple-600" />
          <h4 className="text-sm font-semibold">Automatiche</h4>
          <Badge variant="outline" className="bg-purple-50 text-purple-700 text-xs">
            {autoDeadlines.length}
          </Badge>
        </div>
        <div className="rounded-lg border">
          <Table>
            {tableHeader}
            <TableBody>
              {renderDeadlineTableRows(autoDeadlines)}
            </TableBody>
          </Table>
        </div>
      </div>

      {/* Manual deadlines - secondary */}
      {manualDeadlines.length > 0 && (
        <div className="space-y-2 opacity-75">
          <div className="flex items-center gap-2">
            <PenLine className="h-4 w-4 text-muted-foreground" />
            <h4 className="text-xs font-medium text-muted-foreground">Manuali</h4>
            <Badge variant="outline" className="text-xs">
              {manualDeadlines.length}
            </Badge>
          </div>
          <div className="rounded-lg border">
            <Table>
              {tableHeader}
              <TableBody>
                {renderDeadlineTableRows(manualDeadlines)}
              </TableBody>
            </Table>
          </div>
        </div>
      )}
    </div>
  );
}

function ManualDeadlineEditRow({
  item,
  colSpan,
  onClose,
}: {
  item: DeadlineRecord;
  colSpan: number;
  onClose: () => void;
}) {
  const [state, formAction] = useActionState(updateManualDeadline, undefined);

  useEffect(() => {
    if (state?.success) {
      onClose();
    }
  }, [state?.success, onClose]);

  return (
    <TableRow>
      <TableCell colSpan={colSpan} className="bg-muted/30 p-0 border-l-4 border-l-blue-500">
        <div className="p-4 w-full">
          <form action={formAction} className="flex flex-col gap-4">
            <input type="hidden" name="deadlineId" value={item.id} />

            <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-medium">Tipo</label>
                <select name="type" defaultValue={item.type} className="w-full rounded-md border bg-background px-3 py-2 text-sm" required>
                  <option value="TAGLIANDO">Tagliando</option>
                  <option value="REVISIONE">Revisione</option>
                  <option value="ASSICURAZIONE">Assicurazione</option>
                  <option value="BOLLO">Bollo</option>
                  <option value="REVISIONE_TACHIGRAFO">Rev. Tachigrafo</option>
                  <option value="ALTRO">Altro</option>
                </select>
              </div>

              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-medium">Data scadenza</label>
                <input
                  type="date"
                  name="dueDate"
                  defaultValue={item.dueDate.slice(0, 10)}
                  className="w-full rounded-md border bg-background px-3 py-2 text-sm"
                  required
                />
              </div>

              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-medium">Scadenza km</label>
                <input
                  type="number"
                  name="dueKm"
                  defaultValue={item.dueKm ?? ""}
                  className="w-full rounded-md border bg-background px-3 py-2 text-sm"
                  placeholder="Opzionale"
                />
              </div>

              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-medium">Preavviso (giorni)</label>
                <input
                  type="number"
                  name="reminderDays"
                  defaultValue={item.reminderDays}
                  min={1}
                  max={365}
                  className="w-full rounded-md border bg-background px-3 py-2 text-sm"
                  required
                />
              </div>
            </div>

            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-medium">Descrizione</label>
              <input
                type="text"
                name="description"
                defaultValue={item.description || ""}
                className="w-full rounded-md border bg-background px-3 py-2 text-sm"
              />
            </div>

            <div className="flex items-center gap-3">
              <SubmitButton pendingText="Salvataggio...">Salva modifiche</SubmitButton>
              <Button type="button" variant="outline" onClick={onClose}>Annulla</Button>
              {state?.error ? <p className="text-sm text-destructive">{state.error}</p> : null}
            </div>
          </form>
        </div>
      </TableCell>
    </TableRow>
  );
}
