"use client";

import { useActionState } from "react";
import { createDeadline, toggleDeadlineComplete, deleteDeadline } from "@/lib/actions/deadline-actions";
import { SubmitButton } from "@/components/ui/submit-button";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Plus, Check, Trash2, RotateCcw, Zap, PenLine } from "lucide-react";
import { useState } from "react";
import { deadlineTypeLabels } from "@/lib/labels";

type DeadlineRecord = {
  id: string;
  type: string;
  dueDate: string;
  dueKm: number | null;
  reminderDays: number;
  description: string | null;
  completed: boolean;
  completedDate: string | null;
  autoGenerated: boolean;
};

export function DeadlineTab({
  vehicleId,
  deadlines,
  currentKm,
  canManage,
}: {
  vehicleId: string;
  deadlines: DeadlineRecord[];
  currentKm: number;
  canManage: boolean;
}) {
  const [showForm, setShowForm] = useState(false);
  const [state, formAction] = useActionState(createDeadline, undefined);

  const now = new Date();

  const autoDeadlines = deadlines.filter((d) => d.autoGenerated);
  const manualDeadlines = deadlines.filter((d) => !d.autoGenerated);

  function getDeadlineStatus(d: DeadlineRecord) {
    if (d.completed) return "completed";
    // Check km-based expiry first (for tagliando)
    if (d.dueKm && currentKm >= d.dueKm) return "overdue";
    const due = new Date(d.dueDate);
    if (due < now) return "overdue";
    // Upcoming: within 30 days or within 1000 km of limit
    if (d.dueKm && currentKm >= d.dueKm - 1000) return "upcoming";
    const diff = (due.getTime() - now.getTime()) / (1000 * 60 * 60 * 24);
    if (diff <= 30) return "upcoming";
    return "ok";
  }

  const statusBadge: Record<string, { label: string; className: string }> = {
    completed: { label: "Completata", className: "bg-green-100 text-green-800" },
    overdue: { label: "Scaduta", className: "bg-red-100 text-red-800" },
    upcoming: { label: "In scadenza", className: "bg-orange-100 text-orange-800" },
    ok: { label: "OK", className: "bg-blue-100 text-blue-800" },
  };

  function DeadlineTableRows({ items }: { items: DeadlineRecord[] }) {
    if (items.length === 0) {
      return (
        <TableRow>
          <TableCell colSpan={canManage ? 7 : 6} className="text-center text-muted-foreground py-6">
            Nessuna scadenza
          </TableCell>
        </TableRow>
      );
    }
    return (
      <>
        {items.map((d) => {
          const status = getDeadlineStatus(d);
          const badge = statusBadge[status];
          return (
            <TableRow key={d.id}>
              <TableCell>
                <Badge variant="outline">
                  {deadlineTypeLabels[d.type]}
                </Badge>
              </TableCell>
              <TableCell>
                {new Date(d.dueDate).toLocaleDateString("it-IT")}
              </TableCell>
              <TableCell>
                {d.dueKm ? `${d.dueKm.toLocaleString("it-IT")} km` : "—"}
              </TableCell>
              <TableCell>
                <Badge variant="outline" className={badge.className}>
                  {badge.label}
                </Badge>
              </TableCell>
              <TableCell>{d.reminderDays}gg</TableCell>
              <TableCell className="text-muted-foreground max-w-xs truncate">
                {d.description || "—"}
              </TableCell>
              {canManage && (
                <TableCell>
                  <div className="flex gap-1">
                    <form action={async () => { await toggleDeadlineComplete(d.id); }}>
                      <Button type="submit" variant="ghost" size="icon" className="h-8 w-8" title={d.completed ? "Riapri" : "Completa"}>
                        {d.completed ? (
                          <RotateCcw className="h-4 w-4" />
                        ) : (
                          <Check className="h-4 w-4" />
                        )}
                      </Button>
                    </form>
                    <form action={async () => { await deleteDeadline(d.id); }}>
                      <Button type="submit" variant="ghost" size="icon" className="h-8 w-8 text-destructive" title="Elimina">
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </form>
                  </div>
                </TableCell>
              )}
            </TableRow>
          );
        })}
      </>
    );
  }

  const tableHeader = (
    <TableHeader>
      <TableRow>
        <TableHead>Tipo</TableHead>
        <TableHead>Data Scadenza</TableHead>
        <TableHead>Scadenza Km</TableHead>
        <TableHead>Stato</TableHead>
        <TableHead>Preavviso</TableHead>
        <TableHead>Descrizione</TableHead>
        {canManage && <TableHead>Azioni</TableHead>}
      </TableRow>
    </TableHeader>
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h3 className="font-semibold">Scadenze</h3>
        {canManage && (
          <Button
            variant="outline"
            size="sm"
            onClick={() => setShowForm(!showForm)}
          >
            <Plus className="mr-2 h-4 w-4" />
            Nuova Scadenza
          </Button>
        )}
      </div>

      {showForm && canManage && (
        <form action={formAction} className="rounded-lg border p-4 space-y-4">
          {state?.error && (
            <div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">
              {state.error}
            </div>
          )}
          {state?.success && (
            <div className="rounded-md bg-green-50 p-3 text-sm text-green-700">
              Scadenza salvata
            </div>
          )}
          <input type="hidden" name="vehicleId" value={vehicleId} />
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div className="space-y-2">
              <Label htmlFor="type">Tipo *</Label>
              <select
                id="type"
                name="type"
                className="w-full rounded-md border bg-background px-3 py-2 text-sm"
                required
              >
                <option value="TAGLIANDO">Tagliando</option>
                <option value="REVISIONE">Revisione</option>
                <option value="ASSICURAZIONE">Assicurazione</option>
                <option value="BOLLO">Bollo</option>
                <option value="REVISIONE_TACHIGRAFO">Rev. Tachigrafo</option>
                <option value="ALTRO">Altro</option>
              </select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="dueDate">Data Scadenza *</Label>
              <Input id="dueDate" name="dueDate" type="date" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="reminderDays">Preavviso (giorni)</Label>
              <Input
                id="reminderDays"
                name="reminderDays"
                type="number"
                defaultValue={30}
                min={1}
                max={365}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="description">Descrizione</Label>
              <Input id="description" name="description" />
            </div>
          </div>
          <SubmitButton size="sm" pendingText="Salvataggio...">
            Salva
          </SubmitButton>
        </form>
      )}

      {/* Automatic deadlines - primary */}
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <Zap className="h-4 w-4 text-purple-600" />
          <h4 className="text-sm font-semibold">Automatiche</h4>
          <Badge variant="outline" className="bg-purple-50 text-purple-700 text-xs">
            {autoDeadlines.length}
          </Badge>
        </div>
        <div className="rounded-lg border">
          <Table>
            {tableHeader}
            <TableBody>
              <DeadlineTableRows items={autoDeadlines} />
            </TableBody>
          </Table>
        </div>
      </div>

      {/* Manual deadlines - secondary */}
      {manualDeadlines.length > 0 && (
        <div className="space-y-2 opacity-75">
          <div className="flex items-center gap-2">
            <PenLine className="h-4 w-4 text-muted-foreground" />
            <h4 className="text-xs font-medium text-muted-foreground">Manuali</h4>
            <Badge variant="outline" className="text-xs">
              {manualDeadlines.length}
            </Badge>
          </div>
          <div className="rounded-lg border">
            <Table>
              {tableHeader}
              <TableBody>
                <DeadlineTableRows items={manualDeadlines} />
              </TableBody>
            </Table>
          </div>
        </div>
      )}
    </div>
  );
}
