import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { canUploadDocuments } from "@/lib/auth-utils";
import { syncDocumentValidityDeadline } from "@/lib/auto-deadlines";
import { unlink } from "fs/promises";
import { deriveTripAnomalyThumbnailPath } from "@/lib/file-storage";
import { revalidatePath } from "next/cache";

const TYPES_REQUIRING_VALID_TO = new Set(["ASSICURAZIONE", "CONTRATTO_NOLEGGIO"]);

function parseDateField(value: FormDataEntryValue | null, options?: { endOfDay?: boolean }): Date | null {
  if (typeof value !== "string" || value.trim() === "") {
    return null;
  }

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return null;
  }

  if (options?.endOfDay) {
    parsed.setHours(23, 59, 59, 999);
  } else {
    parsed.setHours(0, 0, 0, 0);
  }

  return parsed;
}

export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: "Non autorizzato" }, { status: 401 });
  }

  if (!canUploadDocuments(session.user.role)) {
    return NextResponse.json({ error: "Non autorizzato" }, { status: 403 });
  }

  const { id } = await params;
  const document = await prisma.document.findUnique({ where: { id } });
  if (!document) {
    return NextResponse.json({ error: "Documento non trovato" }, { status: 404 });
  }

  if (document.tripAnomalyId) {
    return NextResponse.json(
      { error: "Le foto anomalia non sono modificabili" },
      { status: 400 }
    );
  }

  const formData = await request.formData();
  const notesRaw = formData.get("notes");
  const validFromRaw = formData.get("validFrom");
  const validToRaw = formData.get("validTo");

  const validFrom = parseDateField(validFromRaw);
  const validTo = parseDateField(validToRaw, { endOfDay: true });

  if (typeof validFromRaw === "string" && validFromRaw.trim() !== "" && !validFrom) {
    return NextResponse.json({ error: "Data inizio validita non valida" }, { status: 400 });
  }

  if (typeof validToRaw === "string" && validToRaw.trim() !== "" && !validTo) {
    return NextResponse.json({ error: "Data fine validita non valida" }, { status: 400 });
  }

  if (TYPES_REQUIRING_VALID_TO.has(document.type) && !validTo) {
    return NextResponse.json(
      { error: "Per questo tipo documento devi indicare la data di fine validita" },
      { status: 400 }
    );
  }

  if (validFrom && validTo && validTo.getTime() < validFrom.getTime()) {
    return NextResponse.json(
      { error: "La data di fine validita non puo essere precedente alla data di inizio" },
      { status: 400 }
    );
  }

  const notes = typeof notesRaw === "string" && notesRaw.trim() ? notesRaw.trim() : null;

  const updated = await prisma.document.update({
    where: { id },
    data: {
      notes,
      validFrom,
      validTo,
    },
  });

  if (updated.validTo) {
    await syncDocumentValidityDeadline({
      vehicleId: updated.vehicleId,
      documentId: updated.id,
      documentType: updated.type,
      documentName: updated.name,
      validTo: updated.validTo,
    });
  } else {
    await prisma.deadline.deleteMany({
      where: {
        sourceDocumentId: updated.id,
        autoGenerated: true,
      },
    });
  }

  revalidatePath(`/mezzi/${updated.vehicleId}`);
  revalidatePath("/documenti");
  revalidatePath("/scadenze");
  revalidatePath("/");

  return NextResponse.json({ success: true });
}

export async function DELETE(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: "Non autorizzato" }, { status: 401 });
  }

  if (!canUploadDocuments(session.user.role)) {
    return NextResponse.json({ error: "Non autorizzato" }, { status: 403 });
  }

  const { id } = await params;

  const document = await prisma.document.findUnique({ where: { id } });
  if (!document) {
    return NextResponse.json({ error: "Documento non trovato" }, { status: 404 });
  }

  // Delete file from disk
  try {
    await unlink(document.filePath);
  } catch {
    // File may already be gone
  }

  const thumbnailPath = deriveTripAnomalyThumbnailPath(document.filePath);
  if (thumbnailPath) {
    try {
      await unlink(thumbnailPath);
    } catch {
      // Thumbnail may already be gone
    }
  }

  await prisma.deadline.deleteMany({
    where: {
      sourceDocumentId: id,
      autoGenerated: true,
    },
  });

  await prisma.document.delete({ where: { id } });

  revalidatePath(`/mezzi/${document.vehicleId}`);
  revalidatePath("/documenti");
  revalidatePath("/scadenze");
  revalidatePath("/");

  return NextResponse.json({ success: true });
}
